    SELECT 
    CAST(ROW_NUMBER() OVER(ORDER BY EMPLOYEE_ID) AS INTEGER) AS USER_KEY
    ,EMPLOYEE_ID
    ,EMPLOYEE_NAME
    ,DEPARTMENT_ID
    ,EMAIL
    ,PHONE
    ,ADDRESS
    ,HIRE_DATE
    ,EMPLOYMENT_STATUS
    ,MD5_COLUMN
    ,SNOW_INSERT_TIME
    ,SNOW_UPDATE_TIME
    FROM {{ ref('stg_dim_user')}}